#!/bin/bash
# Shell to read source file and copy it to target file

echo -n "Enter source file name : "
read src
echo -n "Enter target file name : "
read targ

if [ ! -f $src ]
then
    echo "File $src does not exist"
    exit 1
elif [ -f $targ ]
then
    echo "File $targ exist, cannot ovewrite"
    exit 2
fi

# copy file

cp $src $targ

# store exit status of above copy command to determine whether coommand 
# is successful or not

status=#?

if [ $status -eq 0 ]
then
    echo 'File copied Successfully'
else
    echo 'Problem Copying File'
fi

