#!/usr/bin/perl -w
use strict;

my %elements;
my $element = "debra";

foreach ("debra","bill","brom"){
$elements{$_} = 1;
};

print " Found: '$element'\n" if (exists $elements{$element});
print " D' oh - '$element' not found\n" unless (exists $elements{$element});

foreach (keys %elements){
print "$_\n";
};
